package Java.empleado;

public class Empleado {

    // Atributos
    String nombre;
    int anioContratacion;
    double salario;
    
    // Constructor
    public Empleado() {
        this.nombre = "";
        this.anioContratacion = 0;
        this.salario = 0.0;
    }

    // Constructor con parametros
    public Empleado(String n, int a, double s) {
        this.nombre = n;
        this.anioContratacion = a;
        this.salario = s;
    }

    // Getters

    // Setters

    // Métodos
    public double toString() {
        return 
    }
}
